### ISSUE TITLE
$tell broken

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/SatanicBot#117]
![screen shot 2017-02-09 at 7 08 44 am](https://cloud.githubusercontent.com/assets/5623501/22782804/d3a2bdb8-ee96-11e6-8d3e-944ba385e831.png)

Eli edit:

Log:
```
2017-02-09T17:12:15.898030+00:00 app[bot.1]: [2017/02/09 17:12:15.897] >> :SatanicSanta!~SatanicSa@216.64.244.206 PRIVMSG #FTB-Wiki :$tell xbony2|afk test
2017-02-09T17:12:15.906962+00:00 app[bot.1]: [2017/02/09 17:12:15.906] !! [New thread] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x007fe3f5a5ee08 @prefix=/^\$/, @pattern=/tell ([a-zA-Z][a-zA-Z0-9\^\-_\|\[\]]+) (.+)/, @suffix=nil>>: #<Thread:0x007fe3f5631d80> -- 1 in total.
2017-02-09T17:12:15.912192+00:00 app[bot.1]: [2017/02/09 17:12:15.911] !! /app/vendor/bundle/ruby/2.3.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:327:in `block in call_hooks': undefined method `hook' for #<Plugins::Commands::Tell:0x007fe3f5a5fa38> (NoMethodError)
2017-02-09T17:12:15.912246+00:00 app[bot.1]: [2017/02/09 17:12:15.912] !! 	/app/vendor/bundle/ruby/2.3.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:322:in `each'
2017-02-09T17:12:15.912344+00:00 app[bot.1]: [2017/02/09 17:12:15.912] !! 	/app/vendor/bundle/ruby/2.3.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:322:in `find'
2017-02-09T17:12:15.912705+00:00 app[bot.1]: [2017/02/09 17:12:15.912] !! 	/app/vendor/bundle/ruby/2.3.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:417:in `block (2 levels) in __register_matchers'
2017-02-09T17:12:15.912411+00:00 app[bot.1]: [2017/02/09 17:12:15.912] !! 	/app/vendor/bundle/ruby/2.3.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:322:in `call_hooks'
2017-02-09T17:12:15.912762+00:00 app[bot.1]: [2017/02/09 17:12:15.912] !! 	/app/vendor/bundle/ruby/2.3.0/gems/cinch-2.3.3/lib/cinch/handler.rb:99:in `block in call'
2017-02-09T17:12:15.912930+00:00 app[bot.1]: [2017/02/09 17:12:15.912] !! [Thread done] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x007fe3f5a5ee08 @prefix=/^\$/, @pattern=/tell ([a-zA-Z][a-zA-Z0-9\^\-_\|\[\]]+) (.+)/, @suffix=nil>>: #<Thread:0x007fe3f5631d80> -- 0 remaining.
```

**Comment by elifoster** [comment]
Fixed by 8573620
